# Generated by Django 3.0.1 on 2021-04-26 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='merchants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('merchant_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_invoice_id', models.IntegerField(default=0)),
                ('Product_type', models.CharField(max_length=120)),
                ('weight', models.FloatField(default=0)),
                ('Division', models.CharField(max_length=120)),
                ('District', models.CharField(max_length=120)),
                ('Street', models.CharField(max_length=120)),
                ('Charge', models.FloatField(default=0)),
                ('Cod_charge_add', models.FloatField(default=0)),
                ('return_charge_add', models.FloatField(default=0)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.merchants')),
            ],
        ),
    ]
